language: php

dist: trusty
php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit --no-coverage
